-- R-Control schema
create extension if not exists "pgcrypto";

create type public.user_role as enum ('admin', 'chef', 'storekeeper', 'viewer');
create type public.plan_status as enum ('draft', 'submitted', 'checked', 'finalized');
create type public.unit_type as enum ('kg', 'g', 'pcs', 'l');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role public.user_role not null default 'viewer',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.kitchens (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.user_kitchens (
  user_id uuid not null references public.profiles(id) on delete cascade,
  kitchen_id bigint not null references public.kitchens(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, kitchen_id)
);

create table if not exists public.kitchen_staff (
  id bigint generated by default as identity primary key,
  kitchen_id bigint not null references public.kitchens(id) on delete cascade,
  full_name text not null,
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (kitchen_id, id)
);

create table if not exists public.plans (
  id bigint generated by default as identity primary key,
  kitchen_id bigint not null references public.kitchens(id) on delete restrict,
  plan_date date not null,
  status public.plan_status not null default 'draft',
  created_by uuid not null references public.profiles(id) on delete restrict,
  submitted_at timestamptz,
  checked_by uuid references public.profiles(id) on delete restrict,
  checked_at timestamptz,
  finalized_by uuid references public.profiles(id) on delete restrict,
  finalized_at timestamptz,
  responsible_1_staff_id bigint,
  responsible_2_staff_id bigint,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (kitchen_id, plan_date),
  constraint plans_responsible_not_equal check (
    responsible_1_staff_id is null
    or responsible_2_staff_id is null
    or responsible_1_staff_id <> responsible_2_staff_id
  ),
  constraint plans_r1_in_kitchen foreign key (kitchen_id, responsible_1_staff_id)
    references public.kitchen_staff(kitchen_id, id),
  constraint plans_r2_in_kitchen foreign key (kitchen_id, responsible_2_staff_id)
    references public.kitchen_staff(kitchen_id, id)
);

create table if not exists public.plan_items (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.plans(id) on delete cascade,
  product_name text not null,
  unit public.unit_type not null,
  planned_qty numeric(14,3) not null check (planned_qty > 0),
  actual_qty numeric(14,3),
  is_checked boolean not null default false,
  storekeeper_comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plan_item_audit (
  id bigint generated by default as identity primary key,
  plan_item_id bigint not null references public.plan_items(id) on delete cascade,
  changed_by uuid not null references public.profiles(id) on delete restrict,
  changed_at timestamptz not null default now(),
  field_name text not null,
  old_value text,
  new_value text,
  reason text,
  source text not null,
  constraint plan_item_audit_reason_required_for_admin check (
    source not in ('admin_fix', 'admin_return_to_check')
    or nullif(trim(coalesce(reason, '')), '') is not null
  )
);

create index if not exists idx_profiles_role on public.profiles(role) where is_active;
create index if not exists idx_user_kitchens_user on public.user_kitchens(user_id);
create index if not exists idx_user_kitchens_kitchen on public.user_kitchens(kitchen_id);
create index if not exists idx_staff_kitchen_active on public.kitchen_staff(kitchen_id, is_active);
create index if not exists idx_plans_kitchen_date on public.plans(kitchen_id, plan_date desc);
create index if not exists idx_plans_status_date on public.plans(status, plan_date desc);
create index if not exists idx_plans_created_by on public.plans(created_by);
create index if not exists idx_plan_items_plan on public.plan_items(plan_id);
create index if not exists idx_plan_item_audit_item_time on public.plan_item_audit(plan_item_id, changed_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger trg_plans_updated_at
before update on public.plans
for each row execute function public.set_updated_at();

create trigger trg_plan_items_updated_at
before update on public.plan_items
for each row execute function public.set_updated_at();
